### ISSUE TITLE
Layout customization panel

### ISSUE THREAD

**Issue by idoshamun** [dailynowco/daily-apps#52]
Following https://github.com/dailynowco/daily/issues/79, we introduce a layout customization panel. The panel drops from the top on request and allow to fully customize the feed.

Prerequisites for implementing this issue:
- [x] #49 Radio button component
- [ ] #50 Add different layout settings to feed
- [x] #51 Add a "small" variant to switch button

![Design](https://user-images.githubusercontent.com/1993245/64988617-89518c00-d8d4-11e9-9b9f-280e6a0dcbf7.png)

**Comment by TxsAdamWest** [comment]
Design looks great!  Can't wait to see this in action!

**Comment by idoshamun** [comment]
@TxsAdamWest thank you, means a lot to us! It will take a bit time but we will nail it.
You can keep track of the progress here.
